### ISSUE TITLE
TimePicker issue in ionic app after updating to ios 14 beta release

### ISSUE THREAD

**Issue by bhargavas12** [VitaliiBlagodir/cordova-plugin-datepicker#286]
Hi,

After updating to ios 14 beta release we are facing issues with native timepicker in ionic4 app.
sample images are below:

![image](https://user-images.githubusercontent.com/50710498/90951476-ec4e8a00-e478-11ea-86b8-61217f41f6d8.png)

![image](https://user-images.githubusercontent.com/50710498/90951487-012b1d80-e479-11ea-8f3f-74b747b8e981.png)

any inputs on this?

Thanks,
Bhargav.

**Comment by itziksha** [comment]
I had an issue as well, and I did some tries.
Currently adding this seems to help:

`if (@available(iOS 13.4, *)){
    self.datePicker.preferredDatePickerStyle = UIDatePickerStyleWheels;
  }`

I added it in "updateDatePicker" function, before this code:

`if (allowOldDates) {
    self.datePicker.minimumDate = nil;
  }`

This returns the picker style back to 'wheel' style.

**Comment by bhargavas12** [comment]
After the latest update from IOS this is fixed. Thanks

**Comment by rhomeister** [comment]
Hi @bhargavas12 could you give some more info about this? We have tens of users complain about the date picker, and we'd love to know in which iOS version this is fixed & how it was fixed. We were also unpleasantly surprised by this sudden design change...

**Comment by itziksha** [comment]
> Hi @bhargavas12 could you give some more info about this? We have tens of users complain about the date picker, and we'd love to know in which iOS version this is fixed & how it was fixed. We were also unpleasantly surprised by this sudden design change...

Hi, 
Did you upgrade the webview from UIWebview to WKWebview? 
If not, this also makes issues in iOS 14 and also mandatory soon by apple.

**Comment by rhomeister** [comment]
Yes we do. We have the following in our config.xml, and are on cordova ios 6.1.1

```
    <preference name="WKWebViewOnly" value="true" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
```

**Comment by itziksha** [comment]
I see... I'm actually in cordova ios5.1.1 and with wkwebview plugin.
Sorry, I'm aware of other thing that you can check...

**Comment by bhargavas12** [comment]
> Hi @bhargavas12 could you give some more info about this? We have tens of users complain about the date picker, and we'd love to know in which iOS version this is fixed & how it was fixed. We were also unpleasantly surprised by this sudden design change...

@rhomeister the issue has been fixed from ios 14 beta 5 release.

**Comment by rhomeister** [comment]
Thanks @bhargavas12. One more follow up question: how has it been fixed? Has the old date picker been restored?

**Comment by rhomeister** [comment]
FYI, we're still seeing this: https://youtu.be/wjtLiHZutbk. The user needs to click a few times to actually open the time picker. Also, if the date is smaller than min date, nothing happens.
